version: "3"

services:
    app:
        build: .
        container_name: html-playground-app
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./uploads:/app/uploads
            - ./projects:/app/projects
            - ./assets:/app/assets
            - ./templates:/app/templates
